export const products = [
    {
      id: 1,
      name: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam a veniam porro!',
      rating: 3,
      href: '#',
      imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-01.jpg',
      imageAlt: "Front of men's Basic Tee in black.",
      price: 3500,
      discount: 0,
      limitedDeal: true,
    },
    {
      id: 2,
      name: 'Consectetur adipisicing elit. Reprehenderit, voluptatibus!',
      rating: 4,
      href: '#',
      imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-01.jpg',
      imageAlt: "Front of men's Bolt Tee in white.",
      price: 4200,
      discount: 800,
      limitedDeal: false,
    },
    {
      id: 3,
      name: 'Voluptatibus, illum sapiente itaque repudiandae, autem doloremque dolorem.',
      rating: 5,
      href: '#',
      imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-page-03-product-01.jpg',
      imageAlt: "Front of men's Intersect Tee in black and gray.",
      price: 5000,
      discount: 0,
      limitedDeal: true,
    },
    {
      id: 4,
      name: 'Cupiditate nesciunt, odit illum ratione eligendi amet quia?',
      rating: 4,
      href: '#',
      imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-02.jpg',
      imageAlt: "Front of men's The Essential Tee in gray.",
      price: 3200,
      discount: 0,
      limitedDeal: false,
    },
    {
      id: 5,
      name: 'Fugit, assumenda. Deleniti placeat ducimus aspernatur exercitationem tempore.',
      rating: 3,
      href: '#',
      imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-02.jpg',
      imageAlt: "Side profile of men's Basic Tee in black.",
      price: 3800,
      discount: 1500,
      limitedDeal: true,
    },
    {
      id: 6,
      name: 'Modi explicabo incidunt ipsum ex rem. Sint eos sequi molestias!',
      rating: 5,
      href: '#',
      imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-page-03-product-02.jpg',
      imageAlt: "Side profile of men's Intersect Tee in black and gray.",
      price: 4600,
      discount: 0,
      limitedDeal: false,
    },
    {
      id: 7,
      name: 'Officiis quod doloribus dolorem, eos labore vel non minus reprehenderit!',
      rating: 4,
      href: '#',
      imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-03.jpg',
      imageAlt: "Side profile of men's The Essential Tee in gray.",
      price: 3100,
      discount: 700,
      limitedDeal: true,
    },
    {
      id: 8,
      name: 'Quasi nisi animi nostrum! Quod tempora, ex laudantium ipsam quibusdam?',
      rating: 3,
      href: '#',
      imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-02.jpg',
      imageAlt: "Side profile of men's Bolt Tee in white.",
      price: 4300,
      discount: 0,
      limitedDeal: false,
    },
    {
      id: 9,
      name: 'Rem nostrum facilis exercitationem minus alias reiciendis labore aspernatur.',
      rating: 5,
      href: '#',
      imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-page-03-product-03.jpg',
      imageAlt: "Back of men's The Essential Tee in gray.",
      price: 4900,
      discount: 0,
      limitedDeal: true,
    },
    {
      id: 10,
      name: 'Saepe provident accusantium vitae quam quos molestiae, nemo similique consequatur.',
      rating: 4,
      href: '#',
      imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-04.jpg',
      imageAlt: "Back of men's Basic Tee in black.",
      price: 3300,
      discount: 0,
      limitedDeal: false,
    },
    {
      id: 11,
      name: 'Temporibus dolorem provident vero, magni velit dolores unde magnam esse soluta!',
      rating: 5,
      href: '#',
      imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-02.jpg',
      imageAlt: "Back of men's Bolt Tee in white.",
      price: 4400,
      discount: 900,
      limitedDeal: true,
    },
    {
      id: 12,
      name: 'Vel veniam atque magnam exercitationem itaque! Ipsam, perferendis at?',
      rating: 3,
      href: '#',
      imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-page-03-product-04.jpg',
      imageAlt: "Back of men's Intersect Tee in black and gray.",
      price: 5100,
      discount: 0,
      limitedDeal: false,
    },
    {
      id: 13,
      name: 'Vel veniam atque magnam exercitationem itaque! Ipsam, perferendis at?',
      rating: 3,
      href: '#',
      imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-page-03-product-04.jpg',
      imageAlt: "Back of men's Intersect Tee in black and gray.",
      price: 5100,
      discount: 0,
      limitedDeal: false,
    },
    {
      id: 14,
      name: 'Vel veniam atque magnam exercitationem itaque! Ipsam, perferendis at?',
      rating: 3,
      href: '#',
      imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-page-03-product-04.jpg',
      imageAlt: "Back of men's Intersect Tee in black and gray.",
      price: 5100,
      discount: 0,
      limitedDeal: false,
    },
    // Add more products as needed...
  ];
  